name: Testes 

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - development
    types: [closed]

jobs:
  test:
    runs-on: ubuntu-latest

  steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js (latest version)
      - name: Set up Node.js latest
        uses: actions/setup-node@v3
        with:
          node-version: 'node' # This will install the latest Node.js version
          cache: 'npm'

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Run Jest tests
      - name: Run Jest Tests
        run: |
          npm run test -- --runInBand --testPathPattern=src/testes